name: Continuous Integration

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun i

            - name: Prettify code
              run: "bunx prettier --config .prettierrc . --write"
